# Generated by Django 2.1.15 on 2021-09-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0008_auto_20210201_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodescription',
            name='input_file',
            field=models.FileField(default=1, upload_to='rerun_input/'),
            preserve_default=False,
        ),
    ]
